name: build-pipeline
on:
  pull_request:
    branches:
      - main
      - v*
    paths:
      - 'pkg/**'
      - 'frontend/**'

jobs:
  get_filters:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      query-service: ${{ steps.filter.outputs.query-service }}
      flattener: ${{ steps.filter.outputs.flattener }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          frontend:
            - 'frontend/**'
          query-service:
            - 'pkg/query-service/**'
          flattener:
            - 'pkg/processors/flattener/**'

  backend-checks:
    runs-on: ubuntu-latest
    needs: get_filters
    if: needs.get_filters.outputs.graphql-server == 'true'  || needs.get_filters.outputs.authentication == 'true' || needs.get_filters.outputs.event-tracker == 'true' || needs.get_filters.outputs.subscriber == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16" # By default, the go version is v1.15 in runner.
      - name: Check Golang imports order
        uses: Jerome1337/goimports-action@v1.0.3
        with:
          goimports-path: ./pkg
      - shell: bash
        run: |
          cd pkg
          make backend-services-checks

  frontend-checks:
    runs-on: ubuntu-latest
    needs: get_filters
    if: ${{ needs.get_filters.outputs.frontend == 'true' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Frontend checks
        shell: bash
        run: |
          make frontend-service-checks

  build-frontend:
    runs-on: ubuntu-latest
    needs:
      - get_filters
      - frontend-checks
    if: ${{ needs.get_filters.outputs.frontend == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build frontend docker image
        shell: bash
        run: |
          make build-frontend-amd64

  build-query-service:
    runs-on: ubuntu-latest
    needs:
      - get_filters
      - backend-checks
    if: ${{ needs.get_filters.outputs.query-service == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build  query-service image
        shell: bash
        run: |
          make build-flattener-amd64

  build-flattener:
    runs-on: ubuntu-latest
    needs:
      - get_filters
      - backend-checks
    if: ${{ needs.get_filters.outputs.flattener == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build flattener docker image
        shell: bash
        run: |
          make build-query-service-amd64
