name: push-pipeline
on:
  push:
    branches:
      - main
      - helm-gh-pages
jobs:
  publish-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Publishing helm
        shell: bash
        env:
          GITHUB_PAGES_REPO: rajdas98/signoz
        run: |
          apt-get update
          apt-get install bash openssl
          bash .github/helm-publish.sh